on:
  repository_dispatch:
    types: webhook

env:
  BUCKET_SLUG: ${{ github.event.client_payload.eventPayload.bucket.slug }} 
  ITERATION_ID: ${{ github.event.client_payload.iteration.id }}
  HCP_ORG_ID: ${{ github.event.client_payload.organization_id }}
  HCP_PROJECT_ID: ${{ github.event.client_payload.project_id }}
  # HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  # HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  # VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
  # VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
  # VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}

jobs:
  delete_revoked_templates:
    runs-on: "ubuntu-latest"
    steps:
      - run: echo $BUCKET_SLUG
      - run: echo $ITERATION_ID
      - run: echo $HCP_ORG_ID
      - run: echo $HCP_PROJECT_ID
    
    