name: HCP Packer Delete Images
on:
  repository_dispatch:
    types: 
      - image_deletion
  workflow_dispatch:
env:
  BUCKET_SLUG: ${{ github.event.client_payload.bucket_slug }} 
  ITERATION_ID: ${{ github.event.client_payload.iteration_id }}
  HCP_ORG_ID: ${{ github.event.client_payload.organization_id }}
  HCP_PROJECT_ID: ${{ github.event.client_payload.project_id }}
  VCENTER_USERNAME: ${{ secrets.VCENTER_USERNAME }}
  VCENTER_PASSWORD: ${{ secrets.VCENTER_PASSWORD }}
  VCENTER_SERVER: ${{ secrets.VCENTER_SERVER }}
  HCP_CLIENT_ID: ${{ secrets.HCP_CLIENT_ID }}
  HCP_CLIENT_SECRET: ${{ secrets.HCP_CLIENT_SECRET }}
  

jobs:
  tag_revoked_images:
    runs-on: [self-hosted, gcve]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1
      - name: Delete Images
        run: pwsh -f ./main.ps1
    
